### PR TITLE
Various changes

### PR DESCRIPTION
**Pull request by Caerbannog**
These commits contain various suggestions, tell me if anything is unwanted.
Hopefully I will find the time to fill more content.

What is the preferred form of root-relative links ? There are uses of  `/download`, `{{ .Site.BaseURL }}`, and even `http://misc.c4757p.com/fe.png`. Should we stick with the first?

### CODE REVIEW

**Comment by marekr** [comment]
Why are you using python web server for testing? Hugo comes with a web server for testing that even has live refreshing on changes.

hugo server -w -v

**Comment by Caerbannog** [comment]
Because I didn't know about it, thank you.

**Comment by marekr** [comment]
No problem just asking.

The rough draft of features is ok. Something I really want done is to have screenshots of said features. People really really like screenshots of software before they download. But whether its part of the features page or another "Screenshots" page I don't know.

**Comment by nickoe** [comment]
@Caerbannog Thank you for contributing.

But as hugo has its own webserver you should just remove the references to the python stuff, and maybe just write another hugo command example if you are dissatisfied with one currently there.

I think we should just use {{ .Site.BaseURL }} everywhere.

When one builds locally with hugo you can override that variable to match your local setup, for example replacing it with your machine ip and or port. Then you can easily test the site on other devices, depending on what your workflow is and such. Just a suggestion.

**Comment by Caerbannog** [comment]
Sorry about the Python stuff, commit 4dca201 replaces it with `hugo server`.

For the base URL, using `href"/index.html"` will work regardless of machine IP or port. Advantage: it can be used in CSS files directly. The only drawback I can see is if you host all the site in a subfolder like `http://myserver/subfolder/index.html`.

**Comment by nickoe** [comment]
I just meged this as is, but what exactly to do with the features page needs to be considered.  But I think it might be usefull to have some more detailed descriptions of it, and a screenshot. Maybe some of the introductory text from the documentaion?

**Pull request merged**
