### PR TITLE
ASCIIDOC defalut icons for warning, tip, etc.

### PR DESCRIPTION
**Pull request by Thor-Arne**

### CODE REVIEW

**Comment by marekr** [comment]
Where are they used?

**Comment by Thor-Arne** [comment]
These icons is supposed to be used for the ASCIIDOC WARNIG:, TIP:, etc. built-in admonition types as described in http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#paragraphs.
The used CSS doesn't parse these yet according to nikoe, but they should be included because it significantly improves the look and usability of the pages.

**Comment by marekr** [comment]
According to the manual of asciidoctor which we use..we don't need icons as it will generate font-awesome compatible HTML (and we already have font-awesome loaded).
http://asciidoctor.org/docs/user-manual/#icons

We just need to add 
:icons: font
to the pages that need it.

**Comment by Thor-Arne** [comment]
As I see it; the full color .png icons is more usable inside a document than the monochrome font based ones. Font based icons looks good on buttons, not inside a document for highlighting a paragraph.

**Comment by marekr** [comment]
Welp, the bigger issue is it seems asciidoctor wants to actually resolve the icons to see if they exist i.e.

:iconsdir: somepath

problem is the path is relative to the adoc file being parsed location, but then the generated <img tag will have the wrong url.

**Comment by Thor-Arne** [comment]
I don't understand how it does that,  it should be a simple CSS issue where the style of the paragraph point to the image. I see other projects use the admonition icons with no trouble at all.

Anyway, I'm not going to discuss this any more.

**Comment by marekr** [comment]
Confusingly enough it seems using:

:icons: fonts
:iconsdir: /img/icons/

causes it work( even though thats supposed to trigger font-awesome css). 

I merged, then moved to a subfolder /icons/ to keep tidy and added some basic CSS for admonition  blocks.

**Pull request merged**
