### PR TITLE
Fileformats

### PR DESCRIPTION
**Pull request by Thor-Arne**
A few things to check, see comments.

### CODE REVIEW

**Comment by Caerbannog** [comment]
You have added some details that might be useful in the documentation:
https://github.com/ciampix/kicad-doc/blob/master/src/KiCad/KiCad.adoc

**Comment by marekr** [comment]
Any reason you made it a html file and not asciidoc? Its nice to keep parity with the kicad-doc repo being in asciidoc and make it easier for people to work with. Unless you need extremely special formatting or look on a page (like downloads.html) that would be tedious with asciidoc.

I'm not a big fan of the teletype tag either. <code> is HTML5 supported and does the monospace appearance, <tt> is obsolete.

**Comment by Thor-Arne** [comment]
First, I'm not familiar with asciidoc. Second, I was told by nikoe to use html.

As this is for a web-page that's going to be styled by css I don't see any reason for not using html, There is not that much text on the page either, It shouldn't be a problem to extract the information to use in other documentation, even if the other documents is in asciidoc.

The teletype tag was used because this was the tag that gave the result closest to what was before,
All the tags used in this document is unstyled, and will change depending on the global styles used.

**Comment by nickoe** [comment]
@Thor-Arne  I am sorry for the confusion I may have caused you. You made the "Made with KiCad" page. Thank you.

For that page I said you should just used HTML, because this is one of those specially formatted pages. But now I see you have figured out how to use git and github pull requests. Good. But THML pages are only intended to be used for specially formatted pages. This page you added, could be much easier to write in asciidoc, and I would rather like it to be as such. I can merge this and then convert it to asciidoc, or I offer you to do it.

**Pull request merged**
